- type: entity
  id: LockerBrigmedicFilledHardsuit
  suffix: Corpsman, Filled, Hardsuit
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
    - id: ClothingEyesGlassesSunglasses # Polonium edit
    - id: WeaponDisabler
    - id: TrackingImplanter
      amount: 2
    - id: ClothingOuterHardsuitBrigmedic # WD EDIT: ClothingOuterHardsuitCombatCorpsman -> ClothingOuterHardsuitBrigmedic
    - id: ClothingUniformJumpsuitBrigmedic
    - id: ClothingUniformJumpskirtBrigmedic
    - id: HandheldGPSBasic # Added GPS because I just think it should be there tbh.
    - id: MedkitFilled
    - id: MedkitCombatFilled
      prob: 0.6
    - id: MedkitAdvancedFilled
      prob: 0.4
    - id: MedkitOxygenFilled
      prob: 0.3
    - id: MedkitBruteFilled
      prob: 0.3
    - id: MedkitToxinFilled
      prob: 0.3
    - id: MedkitBurnFilled
      prob: 0.7
    - id: LunchboxSecurityFilledRandom
      prob: 0.3
    - id: ClothingHandsGlovesNitrile
    - id: ClothingBeltCorpsmanWebbing
    - id: DefibrillatorCompact
    - id: BoxBodyBag
    - id: ClothingMaskGasSecurity
    - id: OxygenTankFilled
